### ISSUE TITLE
Incoming request version mismatch causing error creating resources

### ISSUE THREAD

**Issue by ducttapeprodigy** [vmware/terraform-provider-avi#123]
Avi running v20.1.5 on the controller, using the v20.1.6 TerraForm provider

Trying to create a resource of type avi_vsvip throws the error.

Error: Encountered an error on POST request to URL https://avicontroller/api/vsvip: HTTP code: 400; error from Avi: map[error:Incoming request (v18_2_8) has field (prefix_length) introduced in later versions(v20_1_1).]

We're also getting a similar error creating a resource of type avi_pool

Error: Encountered an error on POST request to URL https://avicontroller/api/pool: HTTP code: 400; error from Avi: map[error:Incoming request (v18_2_8) has field (enable_http2) introduced in later versions(v20_1_1).]

**Comment by ducttapeprodigy** [comment]
We saw the same error/behavior running the Avi Provider v20.1.5

**Comment by simtcrom** [comment]
@ducttapeprodigy 
I had the same issue and got it resolved by adding avi_version = "xxx" to the provider section.
Full details at [https://github.com/vmware/terraform-provider-avi/issues/141](url)

**Comment by yograjshisode** [comment]
We should use the same version of the controller and terraform provider. Also please set avi_version.
