### ISSUE TITLE
avi_systemconfiguration module does not recognize dns_configuration

### ISSUE THREAD

**Issue by bcdurden** [vmware/terraform-provider-avi#133]
I'm attempting to port over a significant amount of bash/curl scripts for configuring Avi over to Terraform and I've run into a roadblock when attempting to set the dns_configuration field in avi_systemconfiguration.

I can clearly see the values imported to the resource when using terraform import.
```bash
❯ terraform state show avi_systemconfiguration.avi_system
resource "avi_systemconfiguration" "avi_system" {
...
dns_configuration {
        server_list {
            addr = "8.8.8.8"
            type = "V4"
        }
    }
}
```

However, when attempting set this value in a module definition, I receive an error that states 'An argument named "dns_configuration" is not expected here'
```bash
❯ cat avi.tf
...
resource "avi_systemconfiguration" "avi_system" {
  uuid = "default"
  dns_configuration = ""
  ssh_ciphers               = [
          "aes128-ctr",
          "aes256-ctr",
        ]
  ssh_hmacs                 = [
          "hmac-sha2-512-etm@openssh.com",
          "hmac-sha2-256-etm@openssh.com",
          "umac-128-etm@openssh.com",
          "hmac-sha2-512",
        ]
  enable_cors = true
  welcome_workflow_complete = true
}
❯ terraform plan

Error: Unsupported argument

  on avi.tf line 9, in resource "avi_systemconfiguration" "avi_system":
   9:   dns_configuration = {}

An argument named "dns_configuration" is not expected here. Did you mean to
define a block of type "dns_configuration"?
```

I know for a fact that this value is changeable using the REST API via the /api/systemconfiguration endpoint. The field is also described in the Avi Terraform documentation. I have a running Avi controller versioned at 20.1.4 and am using the 20.1.6 provider.

**Comment by yograjshisode** [comment]
dns_configuration required block type. 
eg.
```
dns_configuration {
    search_domain = ""
  } 
```
