### ISSUE TITLE
when renaming provider from avi to something else and locally storing provider binary, it still goes to hashicorp/avi/

### ISSUE THREAD

**Issue by simtcrom** [vmware/terraform-provider-avi#181]
We have compiled the source from https://github.com/vmware/terraform-provider-avi/tree/v21.1.1
and kept the binary locally and provider block looks as below

```
terraform {
  required_providers {
    avi = {
	  version = "21.1.1"
      source  = "xxx.xxx/edu/avi"      
    }
  }
}
```

Kept binary at C:\Users\xxxxxxx\AppData\Roaming\terraform.d\plugins\xxx.xxx\edu\avi\21.1.1\windows_amd64\terraform-provider-avi.exe

with above terraform init works fine. terraform providers out put shows as below,

├── provider[xxx.com/edu/avi] 21.1.1
└── module.avi
    └── provider[xxx.com/edu/avi] 21.1.1

**When we try to rename the provider from avi to something else, for eg xxxavi issue starts,**

```
terraform {
  required_providers {
    xxxavi = {
	  version = "21.1.1"
      source  = "xxx.xxx/edu/avi"      
    }
  }
}
```

Kept binary at C:\Users\xxxxxxx\AppData\Roaming\terraform.d\plugins\xxx.xxx\edu\xxxavi\21.1.1\windows_amd64\terraform-provider-xxxavi.exe

terraform init command throws below error

Initializing the backend...

Initializing provider plugins...
- Finding fid.com/edu/xxxavi versions matching "21.1.1"...
**- Finding latest version of hashicorp/avi...**
- Installing fid.com/edu/xxxavi v21.1.1...
- Installed fid.com/edu/xxxavi v21.1.1 (unauthenticated)
╷
│ Error: Failed to query available provider packages
│
**│ Could not retrieve the list of available versions for provider hashicorp/avi: provider registry registry.terraform.io does not have a provider named registry.terraform.io/hashicorp/avi**
│

terraform provider output as below

├── provider[xxx.com/edu/xxxavi] 21.1.1
└── module.avi
    ├── provider[xxx.com/edu/xxxavi] 21.1.1
    └── provider[registry.terraform.io/hashicorp/xxxavi]

Any idea, why is it going to hashicorp/avi?

**Comment by sabalejay** [comment]
Hi @simtcrom , this is not a avi provider issue. You can contact hashicorp / check their documentation for this particular use case.
