### ISSUE TITLE
Resource Creation of Virtual Service with vsvip and pool

### ISSUE THREAD

**Issue by burnsjared0415** [vmware/terraform-provider-avi#321]
### Describe the bug

Based on the examples i have seen and also the error i am getting there is a issue with vrf_context_ref between Pool and Virtual Service. If you look at Pool objects or connect there is no vrf_context listed but there is a vrf_ref. If i set the context as so pool and also on virtual service i am getting: error:VRF Context for API_VCENTER_T and pool test_pool_vcenter different]

Here is the code:
Pool:
data "avi_vrfcontext" "vlan" {
    name = "mgmt"
}

resource "avi_pool" "pool_2_vcenter" {
    name = var.pool_2_name_vcenter
    tenant_ref = "/api/tenant/?name=admin"
	cloud_ref = data.avi_cloud.avi_cloud_name_vcenter.id
	enabled = true
	vrf_ref = data.avi_vrfcontext.vlan.id
	default_server_port = var.pool_2_default_server_port_vcenter
	lb_algorithm = "LB_ALGORITHM_ROUND_ROBIN"
	health_monitor_refs = [data.avi_healthmonitor.monitor.id]
    placement_networks {
           network_ref = data.avi_network.vcenter_network.id
            subnet {
		     ip_addr {
		      addr = var.avi_vcenter_placement_network
			  type = "V4"
			 }
            mask = var.avi_vcenter_placement_network_mask
           }
	}	
}

resource "avi_server" "server_2_pool_1_vcenter" {
	for_each = var.pool_member_vcenter_list
	ip = each.value.ip_address
	pool_ref = avi_pool.pool_2_vcenter.id
	hostname = each.value.hostname
	enabled = true
}
Virtual Service VIP
data "avi_vrfcontext" "vlan" {
    name = "mgmt"
}

resource "avi_vsvip" "virtual_service_2_vip_vcenter" {
    for_each = var.virtual_service_list_vcenter
	name = each.value.virtual_service_name
    tenant_ref = "/api/tenant/?name=admin"
	cloud_ref = data.avi_cloud.avi_cloud_name_vcenter.id
	vrf_context_ref = data.avi_vrfcontext.vlan.id
	vip {
		vip_id = each.value.virtual_service_id
		ip_address {
		 type = "V4"
		 addr = each.value.virtual_service_1_vip_ip_addr
        }
        placement_networks {
           network_ref = data.avi_network.vcenter_network.id
           subnet {
		    ip_addr {
		      addr = var.avi_vcenter_placement_network
			  type = "V4"
			}
            mask = var.avi_vcenter_placement_network_mask
           }
		}
	}
}
Virtual Service
data "avi_vrfcontext" "vlan" {
    name = "mgmt"
}
data "avi_pool" "vcenter_pool" {
    name = var.avi_vcenter_pool_name
}
data "avi_vsvip" "vsvip_2_vcenter" {
    name = var.avi_vsvip_1_name_vcenter
}
resource "avi_virtualservice" "vip_1_nsx" {
    name = var.avi_virtual_service_name_nsxt
    tenant_ref = "/api/tenant/?name=admin"
	cloud_ref = data.avi_cloud.nsxt_cloud.id
	pool_ref = data.avi_pool.nsxt_pool.id
	vrf_context_ref = data.avi_vrfcontext.segment.id
	vsvip_ref = data.avi_vsvip.vsvip_1_nsxt.id
	application_profile_ref = data.avi_applicationprofile.application_profile_1.id
	se_group_ref = data.avi_serviceenginegroup.nsxt_cloud.id
	services {
	 port = var.avi_virtual_service_port_nsxt
	}
}

### Reproduction steps

```bash
1.I have checked other peoples code on GitHub and they don't reference vrf_context but if you don't reference the context it throws the same error
2.
3.
...
```

### Expected behavior

I am expecting it to create the virtual service

**Comment by sabalejay** [comment]
Hi @burnsjared0415, setting a different context for Pool and VS is not allowed by the AVI Controller.
