### ISSUE TITLE
serviceenginegroup showing 500 reponse 

### ISSUE THREAD

**Issue by amitchandpurkar** [vmware/terraform-provider-avi#329]
### Describe the bug

AVI version :- 21.1.2 
Terraform Version :- .13.5 

module.avi-config-systemconfiguration.null_resource.ntp_server_key_workaround: Creation complete after 1s [id=6357873502358716222]

Error: Encountered an error on PUT request to URL https://10.171.111.195/api/serviceenginegroup/serviceenginegroup-5b570e8b-7b1a-4426-bdfe-eb4eff5eb5e1?skip_default=true: HTTP code: 500.

Error: Provider produced inconsistent result after apply

When applying changes to
module.avi-config-network.avi_network.networks["avi"], provider
"registry.terraform.io/vmware/avi" produced an unexpected new value: Root
resource was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Reproduction steps

```bash
1. re-run the terraform apply ... validate logs on AVi controller 
attaching logs as an attachment
```

### Expected behavior

 put call should be 200 response code : https://10.171.111.195/api/serviceenginegroup/serviceenginegroup-5b570e8b-7b1a-4426-bdfe-eb4eff5eb5e1?skip_default=true

**Comment by amitchandpurkar** [comment]
[terraform_v0.13.5_IAD.txt](https://github.com/vmware/terraform-provider-avi/files/8065087/terraform_v0.13.5_IAD.txt)

**Comment by chandanapatnala** [comment]
Not reproducible
