### ISSUE TITLE
Provider crash during avi_serviceenginegroup destroy

### ISSUE THREAD

**Issue by matteo-magni** [vmware/terraform-provider-avi#376]
### Describe the bug

When destroying `avi_serviceenginegroup` resources the provider crashes with the following stacktrace:
```
avi_serviceenginegroup.default: Destroying... [id=https://xxx.xxx.xxx.xxx/api/serviceenginegroup/serviceenginegroup-12f5a713-21b4-4356-a02a-25c0cf61bde4]
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-avi_v21.1.4 plugin:

panic: interface conversion: interface {} is string, not int

goroutine 83 [running]:
github.com/vmware/terraform-provider-avi/avi.resourceAviServiceEngineGroupDelete(0x140005eb698?, {0x1013c7340?, 0x14000075680})
        github.com/vmware/terraform-provider-avi/avi/resource_avi_serviceenginegroup.go:1669 +0x538
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0x10121f52e?, {0x10158d4e0?, 0x14000650680?}, 0x24?, {0x1013c7340?, 0x14000075680?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:369 +0x138
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400010c9a0, {0x10158d4e0, 0x14000650680}, 0x140009d3930, 0x14000311400, {0x1013c7340, 0x14000075680})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/resource.go:428 +0x2fc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x140003127c8, {0x10158d4e0, 0x14000650680}, 0x140010b2e10)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.8.0/helper/schema/grpc_provider.go:977 +0xb40
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0x140001bb080, {0x10158d588?, 0x14000cbbaa0?}, 0x140006c2000?)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0x68
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x10152f9c0?, 0x140001bb080}, {0x10158d588, 0x14000cbbaa0}, 0x14001242420, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x174
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002a0e00, {0x10158fea8, 0x14000bce000}, 0x14000374400, 0x14000b48bd0, 0x101a679c0, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1194 +0xaf0
google.golang.org/grpc.(*Server).handleStream(0x140002a0e00, {0x10158fea8, 0x14000bce000}, 0x14000374400, 0x0)
        google.golang.org/grpc@v1.32.0/server.go:1517 +0x840
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.32.0/server.go:859 +0x88
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.32.0/server.go:857 +0x298

Error: The terraform-provider-avi_v21.1.4 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Reproduction steps

1. Create `avi_serviceenginegroup` resource (as well as its dependencies), say it's named `group`
2. Comment out the `avi_serviceenginegroup` resource code and run `terraform apply -auto-approve`
or
Run `terraform destroy -auto-approve` (WARNING: it will destroy everything tracked in the state file)
or
Run `terraform taint avi_serviceenginegroup.group && terraform apply -auto-approve`
3. See the error

### Expected behavior

The `avi_serviceenginegroup` resource gets simply destroyed with no errors.

### Additional context

Provider version tested is 21.1.4.

**Comment by seagyn** [comment]
Can  confirm. It's trying to type cast a string on the interface and it isn't happy about that.

Specifically, this line https://github.com/vmware/terraform-provider-avi/blob/a88d17f8f912866e05297dfe97764a378b5bfe4c/avi/resource_avi_serviceenginegroup.go#L1704

If we can please have a look at this as a matter of urgency.

**Comment by chandanapatnala** [comment]
Not reproducible

**Comment by petersumma** [comment]
Reproduced the Error - same problem still exists.

**Comment by chandanapatnala** [comment]
Hi , Can you please specify the controller version , controller build number, go version and the resource dependencies being used?

**Comment by petersumma** [comment]
> 

Controller: 20.1.7 Build: 9154
terraform provider avi: 21.1.3 
terraform: 1.1.4

**Comment by chandanapatnala** [comment]
Can you please also specify the inputs being configured in the ServiceEngine group resource creation

**Comment by petersumma** [comment]
Nothing special except, "lifecycle { ignore_changes= [ vcenter_clusters, se_dp_max_hb_version]}

resource:
resource "avi_serviceenginegroup" "my-segroup" {
 
  name       = var.avi_segroup.name
  tenant_ref = data.avi_tenant.tenant.id
 
  se_name_prefix = var.avi_segroup.prefix
  vcenter_folder = var.avi_segroup.vcenter_folder
  vcpus_per_se   = var.avi_segroup.cpu
  memory_per_se  = var.avi_segroup.memory
  disk_per_se    = var.avi_segroup.disk_per_se
 
  vcenter_datastores {
    datastore_name = var.avi_segroup.datastore
  }
  vcenter_datastores_include = true
  vcenter_datastore_mode     = "VCENTER_DATASTORE_SHARED"
 
  vcenter_clusters {
    include      = true
    cluster_refs = [var.avi_segroup.cluster_ref]
  }
 
  ha_mode              = "HA_MODE_LEGACY_ACTIVE_STANDBY"
  algo                 = "PLACEMENT_ALGO_DISTRIBUTED"
  se_deprovision_delay = 1440
  active_standby       = true
  app_cache_percent    = 0
  hm_on_standby        = false
  mem_reserve          = false
  se_dp_max_hb_version = 2
  license_tier         = "ENTERPRISE"
  buffer_se            = 0
  max_se               = 2
  max_scaleout_per_vs  = 2
  min_scaleout_per_vs  = 2
 
  lifecycle {
    ignore_changes = [
      vcenter_clusters, se_dp_max_hb_version,
    ]
  }
}
