### ISSUE TITLE
provider should taint vsphere avi_clouds that have different URLs

### ISSUE THREAD

**Issue by carlosonunez-vmw** [vmware/terraform-provider-avi#381]
### Describe the bug

When you change the name or URL of a vSphere cloud in your Terraform configuration, upon running `terraform apply`, one gets this error:

```
│ Error: Encountered an error on PUT request to URL https://localhost:8443/api/cloud/cloud-5f580670-c238-44f0-90c2-8c26b26178a5?skip_default=true: HTTP code: 400; error from Avi: map[error:Change of Vcenter URL/Datacenter for a vCenter cloud is not supported. Please delete the cloud and create a new one]
│
│   with avi_cloud.cloud,
│   on avi.tf line 37, in resource "avi_cloud" "cloud":
│   37: resource "avi_cloud" "cloud" {
│
```

The "Terraform way" of handling this is to taint the resource if immutable properties change and then automatically delete-then-create on the `apply`.

### Reproduction steps

```bash
1. Create a `.tf` file to create an `avi_cloud` resource with a `vcenter_configuration` block
2. Run `terraform apply`
3. Change the URL in the `vcenter_configuration` block
4. Run `terraform apply` again
```

### Expected behavior

1. `terraform plan` should show a `+/-` against the entire `avi_cloud` resource
2. `terraform apply` should delete the cloud then recreate it.

**Comment by adamfowleruk** [comment]
I have replicated this using terraform with Avi 21.1.2, but without even changing the name of the Default-Cloud (I'm presuming the UUID changes upon reconfiguration or similar, so the ID is changed, causing terraform to delete and recreated).

No change was made to the cloud configuration between runs. This error occurred on the second run after applying the configuration successfully. The first run after resulted in the cloud being destroyed. (i.e. DELETE /avi/cloud )

```sh

│ Error: Encountered an error on PUT request to URL https://10.220.50.10/api/cloud/cloud-583cf9bd-cf88-4558-9965-1c782fe6df6d?skip_default=true: HTTP code: 400; error from Avi: map[error:Change of Vcenter URL/Datacenter for a vCenter cloud is not supported. Please delete the cloud and create a new one]
│
│   with module.avi-config.avi_cloud.default_cloud,
│   on 05_avi_configure/main.tf line 81, in resource "avi_cloud" "default_cloud":
│   81: resource "avi_cloud" "default_cloud" {
```

**Comment by adamfowleruk** [comment]
I know how this occurs now. When terraform applies a DELETE to the default cloud the configuration is not reset. Thus if there's any mistake in the URL (which ISNT a URL, but a hostname alone), username, or password then you can never reconfigure this with Terraform.

Much better to avoid using Default-Cloud entirely when using Terraform as the semantics don't mix well with Avi's behaviour for the DELETE /avi/cloud command.

This should be added as documentation, and ideally a warning be printed in terraform when doing a delete / create / update to Default-Cloud.

**Comment by sabalejay** [comment]
Hi @adamfowleruk , directly updating the vSphere Cloud in the terraform configuration is not supported. The correct way to do this is to firstly destroy all the stale references, then destroy the cloud and then recreate the same with a different cloud name.
