### ISSUE TITLE
Provider does not pass through error descriptions from REST API

### ISSUE THREAD

**Issue by adamfowleruk** [vmware/terraform-provider-avi#390]
### Describe the bug

The Avi terraform provider is a thin wrapper for the Avi Go wrapper, and Avi REST API. It is quite common (resource systemconfiguration) to get HTTP 500 errors with no explanatory text or details.

This makes it impossible to debug any incorrect settings in a terraform module using the avi provider.

Please investigate the possibility of passing these through to the terraform error output by using the diagnostics mechanism, as per hashicorp terraform provider best practice.

### Reproduction steps

```bash
1. Apply a resource systemconfiguration with a few fields that are non-trivial (E.g. ntp settings)
2. See HTTP 500 returned with no explanatory details
3.
...
```

### Expected behavior

Any error message or details from the remote server should be passed to the terraform CLI output, with full explanation passed on, rather than just a HTTP status returned with no details.

**Comment by adamfowleruk** [comment]
Example
```sh
module.avi-controller.avi_systemconfiguration.avi_system_config: Creating...
module.avi-controller.avi_systemconfiguration.avi_system_config: Still creating... [10s elapsed]
╷
│ Error: Encountered an error on PUT request to URL https://10.220.50.10/api/systemconfiguration?skip_default=true: HTTP code: 500.
│
│   with module.avi-controller.avi_systemconfiguration.avi_system_config,
│   on 04_avi_controller/main.tf line 152, in resource "avi_systemconfiguration" "avi_system_config":
│  152: resource "avi_systemconfiguration" "avi_system_config" {
```

This is literally all the information provided. systemconfiguration is the most complex call so really you need a lot more than this.

**Comment by itlinux** [comment]
this repo has the block you may want to compare to https://github.com/vmware/terraform-provider-avi/blob/eng/examples/aws/cluster_stages/3_avi_cluster/avi_cluster.tf

**Comment by chandanapatnala** [comment]
Issue is fixed and will be applicable from the next version release
