### ISSUE TITLE
Doc in https://registry.terraform.io not properly formatted

### ISSUE THREAD

**Issue by aburke-incomm** [vmware/terraform-provider-avi#395]
### Describe the bug

the Avi_pool page in https://registry.terraform.io/providers/vmware/avi/latest/docs/resources/avi_pool is not properly formatted and is missing descriptions as a result.

### Reproduction steps

```bash
1.Navigate to https://registry.terraform.io/providers/vmware/avi/latest/docs/resources/avi_pool#argument-reference
2. look at page...
```

### Expected behavior

Page should look more like this [one](https://registry.terraform.io/providers/vmware/avi/latest/docs/resources/avi_virtualservice#argument-reference) for the virtual service

**Comment by sabalejay** [comment]
Hi @aburke-incomm, the issue has been fixed. Thanks.

**Comment by aburke-incomm** [comment]
@sabalejay please provide me with the updated link, the current page does not seem to be any better. Was there a merge or a code fix to repair this?

![2022-11-08_12-35-13](https://user-images.githubusercontent.com/68410284/200647565-0c13e5d1-d599-43fc-8b27-a9da1079fd08.png)

**Comment by sabalejay** [comment]
Hi @aburke-incomm, The update to the documentation would be released in the next version,
