### ISSUE TITLE
cannot use provider from parent module

### ISSUE THREAD

**Issue by slabast** [vmware/terraform-provider-avi#459]
### Describe the bug

when specifying the provider in the parent module as per https://www.terraform.io/language/modules/develop/providers.
The Child module does not log in to AVI

### Reproduction steps

```bash
1.parent module code
terraform {
  required_version = ">=1.0.10"
  required_providers {
    avi = {
      source = "vmware/avi"
      version = "22.1.1"
    }
  }
}
provider "avi" {
  alias           = "prod"
  avi_version     = x.y.z
  avi_controller  = "#######"
  avi_username    = "#######"
  avi_password    = "#######"
}
module "avi_lb" {
    source                  = "git::https://some_source"
    providers      = { avi = avi.prod }
    cloud          = "avicloudname"
}
output "alb_cloud" {
  value = module.avi_lb.alb_cloud
}


2.child module code
terraform {
    required_version = ">=1.0.10"
  required_providers {
    avi = {
      source  = "vmware/avi"
      version = "22.1.1"
    }
  }
}
variable "cloud" {
  description = "ALB cloud Name"
  type = string
}
data "avi_cloud" "nsx_cloud" {
  name      = var.cloud
}
output "alb_cloud" {
    value = data.avi_cloud.nsx_cloud
}

3.when executing the above code the output is stuck on keep reading until it times out with a null value
the user does not show an attempt at logging in to the AVI controller
```

### Expected behavior

Being able to connect to AVI with the provider being specified in the parent (root) module section.
https://www.terraform.io/language/modules/develop/providers
A module intended to be called by one or more other modules **must not** contain any provider blocks. A module containing its own provider configurations is not compatible with the for_each, count, and depends_on arguments that were introduced in Terraform v0.13.

### Additional context

The code above works if the provider section is defined in the child module instead of being passed from the parent module.

**Comment by slarimore02** [comment]
Hey @slabast I can't reproduce this issue in my environment and your code works fine for me. Can you set the TF_LOG=debug environment variable and post the output from a terraform apply?
