### ISSUE TITLE
Error creating avi_cloud resource

### ISSUE THREAD

**Issue by seagyn** [vmware/terraform-provider-avi#506]
### Describe the bug

We are trying to create a cloud but running into what seems to be an issue with a removed API end point.

AVI version: 22.1.2
Provider version: 22.1.2

When we're trying to add the cloud, the configuration is added but the management network fails to get added correct and our TF outputs the following error:

```[ERROR] vertex "avi_cloud.cloud" error: Encountered an error on GET request to URL https://10.100.10.21/api/vimgrvcenterruntime?cloud_uuid=cloud-71fed51a-a442-4fcb-a8d2-3ef8da8cd5be: HTTP code: 404; error from Avi: <nil>```

From what we understand, the `vimgrvcenterruntime` endpoint has been removed in version 22.1.x

Is there something that needs to be updated in the provider or do we need to modify something on this side?

### Reproduction steps

1. Create cloud resource
2. Apply terraform

### Expected behavior

We should get a working cloud config with no errors.

**Comment by seagyn** [comment]
Having looked at the latest release and specifically, #486, it seems that this was fixed but perhaps there is an issue with the release?

**Comment by seagyn** [comment]
Seems like this is the issue, if you look at the tag that was used for the release, the old code still exists there: https://github.com/vmware/terraform-provider-avi/blob/v22.1.2/avi/resource_avi_cloud.go#L293-L321

@chaitanyaavi it seems like the release was run after a commit from @yograjshisode (https://github.com/vmware/terraform-provider-avi/commit/90cd4ee65e703c913231c5a1875c6f03d2eed181)

**Comment by sabalejay** [comment]
Hi @seagyn, I have created a PR to fix the same. We could not merge it the last time since the branch was closed for merging.

**Comment by seagyn** [comment]
Hi @sabalejay thanks for getting back to me.

So just to understand, you're going to patch it your side? I did create a PR as well (#507)

**Comment by sabalejay** [comment]
Hi @seagyn , I have made a patch release. I have also tested the cloud creation post that.

**Comment by seagyn** [comment]
@sabalejay thanks so much. We'll bump back up to the latest and test next week.

**Comment by seagyn** [comment]
@sabalejay we are getting another error:

```Error: didn't get expected state CLOUD_STATE_PLACEMENT_READY in cloud-inventory. Current State: CLOUD_STATE_PLACEMENT_READY```

same code works on 21.* so not sure what's missing. If we cancel the TF the cloud starts working just fine.

**Comment by seagyn** [comment]
@sabalejay I can see the issue. A lot of the TF hasn't been tested for subsequent applies. It only seems tested on single creation and not updating resources that are in place.

Running the cloud resource again assumes that the cloud state will fail because lack of management network (we at least the correct value) and this fails because the cloud state does not go into failed state.

The assumption most likely lives in the fact that subsequent applies will ALWAYS make changes because the management network in TF is ALWAYS different to the resources value because it is modified. Please try this your side to view how poor this is for correct usage of IAC.

I'm more than happy to show you this on a call and if there is something we are missing, you can show us but I suspect there is nothing we are...
