### ISSUE TITLE
Running avi_cloud with vcenter configuration always has changes

### ISSUE THREAD

**Issue by seagyn** [vmware/terraform-provider-avi#510]
### Describe the bug

When running the `avi_cloud` resource, the vcenter_configuration always has drift. It looks as though the `management_network` is getting update with the actual id of the resource in avi where as the argument is simply the name of the network.

In my opinion, the id of the management network should be set as a separate attribute and read in to that when running a plan or refresh

### Reproduction steps

1. Create an avi_cloud resource with vcenter_configuration referencing a VSphere network (by name)
2. Apply the terraform
3. Once finished, run a plan and see the vcenter_configuration block having to be reapplied.

### Expected behavior

As the underlying is not actually being changed (just merely the reference), I would except the terraform not to want to make any changes.

### Additional context

This does apply to many other resources such as `avi_sslkeyandcertificate` which doesn't allow for updates as the resource now contains certificate data. Perhaps this should force replacement if any values change.

**Comment by sabalejay** [comment]
Hi @seagyn, for resources having sensitive fields, the web app does not return it to the provider. So there will always be a diff for resources having sensitive fields.

**Comment by seagyn** [comment]
Hi @sabalejay it's not the sensitive fields that are causing the drift, it's the management_network string. As mentioned, the value expected in the argument gets replaced by an ID by Avi. So it will always want to try and update that even though, theoretically, it hasn't changed.

I believe the correct way would be to set the ID as an attribute so that the argument always remains the same.

**Comment by msartor92** [comment]
As already told it happens on many other resources, this is quite annoying if working in a large context with hundreds of resources

```
Terraform will perform the following actions:

  # module.l7-https-vs.avi_virtualservice.tf_https will be updated in-place
  ~ resource "avi_virtualservice" "tf_https" {
      ~ cloud_type                         = "CLOUD_VCENTER" -> "CLOUD_NONE"
        id                                 = "https://<domain>/api/virtualservice/virtualservice-0c16d725-de59-4274-b15b-10c8dca69111"
        name                               = "tf_https_vs"
        # (35 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by pandvan** [comment]
I can confirm we're also affected by this issue
