### ISSUE TITLE
Custom tenant issue with avi_pool resource

### ISSUE THREAD

**Issue by m-garrido** [vmware/terraform-provider-avi#511]
### Describe the bug

When we pass a custom "tenant_ref" to "avi_pool" resource, this one is created within admin tenant.
Then, if we re-run "terraform apply". Terraform wants to update the "tenant_ref" of the "avi_pool" resource. But, the API returns an error because this parameter is immutable.

```
Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the
following plan may include actions to undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  # avi_pool.waf_pool will be updated in-place
  ~ resource "avi_pool" "waf_pool" {
        id                                    = "https://*****/api/pool/pool-b2c934db-827f-4018-8174-8668b2224365"
        name                                  = "*****"
      ~ tenant_ref                            = "https://*****/api/tenant/admin" -> "/api/tenant/tenant-ccb42242-f9c6-4503-9469-7ef5bc979987"
        # (37 unchanged attributes hidden)

      ~ servers {
            # (7 unchanged attributes hidden)

          + ip {
              + addr = "10.x.y.z"
              + type = "V4"
            }
            # (1 unchanged block hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

avi_pool.waf_pool: Modifying... [id=https://*****/api/pool/pool-b2c934db-827f-4018-8174-8668b2224365]
╷
│ Error: Encountered an error on PUT request to URL https://*****/api/pool/pool-b2c934db-827f-4018-8174-8668b2224365?skip_default=true: HTTP code: 400; error from Avi: map[error:Tenant can not be updated]
│
│   with avi_pool.waf_pool,
│   on resources.tf line 5, in resource "avi_pool" "waf_pool":
│    5: resource "avi_pool" "waf_pool" {
```

### Reproduction steps

1. Create "avi_pool" resource with tenant_ref parameter set to custom tenant (new resource or data)
2. terraform apply
3. terraform apply
...

### Expected behavior

When firstly created, the pool must be directly in custom tenant.

### Additional context

Terraform 1.3.3
Avi network provider 22.1.2

**Comment by m-garrido** [comment]
I've activated TF_LOG to DEBUG level in order to have much informations.
I get this stack :
`2022-12-06T14:58:12.623+0100 [WARN]  Provider "provider[\"registry.terraform.io/vmware/avi\"]" produced an unexpected new value for avi_pool.waf_pool, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .tenant_ref: was cty.StringVal("https://x.x.x.x/api/tenant/org1_platform1_client1"), but now cty.StringVal("https://x.x.x.x/api/tenant/admin")
avi_pool.waf_pool: Creation complete after 4s [id=https://x.x.x.x/api/pool/pool-0fb66224-30c1-4896-8811-48f04faa96c5]`

**Comment by chandanapatnala** [comment]
Hi,
The tenant details should be provided in the credentials to overcome this issue-

`provider "avi" {
  avi_username   = "admin"
  avi_tenant     = "custom"
  avi_password   = var.avi_password
  avi_controller = var.avi_controller
  avi_version    = "22.1.3"
  avi_api_timeout    = 50
}
`
