### ISSUE TITLE
avi_useraccount.avi_user error with provider 

### ISSUE THREAD

**Issue by CodeNoob01** [vmware/terraform-provider-avi#538]
### Describe the bug

│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to avi_useraccount.avi_user, provider "provider[\"registry.terraform.io/vmware/avi\"]"   
│ produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker

### Reproduction steps

When deploying the step on aws example to create staged cluster, i got following error on changing current password.
Module:
2# 2_avi_user_account

### Expected behavior

  # avi_useraccount.avi_user will be created
  + resource "avi_useraccount" "avi_user" {
      + id           = (known after apply)
      + old_password = (sensitive value)
      + password     = (sensitive value)
      + username     = "admin"

**Comment by Rohan-sss1** [comment]
This issue is fixed in 30.2.1 avi provider version.
