### ISSUE TITLE
Wrong feedback if using wrong credentials

### ISSUE THREAD

**Issue by benzander** [vmware/terraform-provider-avi#544]
### Describe the bug

If using wrong credentials and doing a terraform plan there is no error message. The plan will show that all ressources need to be created again.

**If you go ahead and try to apply the plan it will break the statefile which is very critical!**

### Reproduction steps

Deploy any ressources, change password to a wrong value and do a plan again

### Expected behavior

Show helpful error message in case the terraform provider cannot authenticate to the avi controller.

**Comment by Rohan-sss1** [comment]
@benzander Handled the error scenarios properly and it is part of 22.1.5 release so closing this issue.
